create table acceptedmeasures
(
    measure_id bigint generated by default as identity
        primary key,
    name       varchar(255) not null
);

alter table acceptedmeasures
    owner to postgres;

create table cablebrands
(
    cable_id   bigint generated by default as identity
        primary key,
    cable_type varchar(50)  not null,
    name       varchar(255) not null
);

alter table cablebrands
    owner to postgres;

create table employees
(
    employee_id integer generated by default as identity
        primary key,
    department  varchar(255) not null,
    full_name   varchar(255) not null,
    position    varchar(255) not null
);

alter table employees
    owner to postgres;

create table incident_causes
(
    cause_id bigint generated by default as identity
        primary key,
    name     varchar(255) not null
);

alter table incident_causes
    owner to postgres;

create table incidentstatus
(
    status_id bigint generated by default as identity
        primary key,
    name      varchar(255) not null,
    note      varchar(255)
);

alter table incidentstatus
    owner to postgres;

create table it_service_catalog
(
    service_id   bigint generated by default as identity
        primary key,
    service_name varchar(255) not null
);

alter table it_service_catalog
    owner to postgres;

create table layingmethods
(
    method_id bigint generated by default as identity
        primary key,
    name      varchar(255) not null
);

alter table layingmethods
    owner to postgres;

create table locations
(
    location_id bigint generated by default as identity
        primary key,
    address     varchar(255) not null,
    region      varchar(255) not null
);

alter table locations
    owner to postgres;

create table administrativeobjects
(
    object_id   integer generated by default as identity
        primary key,
    name        varchar(255) not null,
    location_id bigint
        constraint fk7jmmjnxuhupam8l3f91v5d4f1
            references locations
);

alter table administrativeobjects
    owner to postgres;

create table optical_fiber_line_types
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255) not null
);

alter table optical_fiber_line_types
    owner to postgres;

create table optical_fiber_lines
(
    id                       bigint generated by default as identity
        primary key,
    name                     varchar(255) not null,
    administrative_object_id integer
        constraint fk5j2u5iggmccqlr36rr081evrd
            references administrativeobjects
);

alter table optical_fiber_lines
    owner to postgres;

create table productionobjects
(
    production_object_id integer generated by default as identity
        primary key,
    name                 varchar(255) not null,
    admin_object_id      integer
        constraint fk1fot1yvd1q4e53j3ghia5ol85
            references administrativeobjects
);

alter table productionobjects
    owner to postgres;

create table horizons
(
    horizon_id           integer generated by default as identity
        primary key,
    name                 varchar(255) not null,
    production_object_id integer
        constraint fkbl9si0lbdv22nbco6bmmaw83n
            references productionobjects
);

alter table horizons
    owner to postgres;

create table request_types
(
    type_id    bigint generated by default as identity
        primary key,
    type_name  varchar(255) not null,
    service_id bigint       not null
        constraint fk7wavc3cscqfjaqmcglf5vl6yd
            references it_service_catalog
);

alter table request_types
    owner to postgres;

create table requestextensioncauses
(
    cause_id bigint generated by default as identity
        primary key,
    name     varchar(255) not null
);

alter table requestextensioncauses
    owner to postgres;

create table requeststatus
(
    status_id bigint generated by default as identity
        primary key,
    name      varchar(255) not null
);

alter table requeststatus
    owner to postgres;

create table roles
(
    role_id   bigint generated by default as identity
        primary key,
    role_name varchar(50) not null
);

alter table roles
    owner to postgres;

create table supportgroup
(
    group_id bigint generated by default as identity
        primary key,
    name     varchar(255) not null
);

alter table supportgroup
    owner to postgres;

create table incidentrequests
(
    request_id            bigint generated by default as identity
        primary key,
    additional_info       varchar(255),
    cable_length          double precision,
    incident_description  text         not null,
    incident_photo        bytea,
    initiator_name        varchar(255) not null,
    redirect_count        integer,
    registration_datetime timestamp,
    total_fibers          integer,
    admin_object_id       integer
        constraint fkg1sjkib00b1w4rs8knmhtcqwq
            references administrativeobjects,
    fiber_brand_id        bigint
        constraint fkfakue78mhgddo4dn2qm162jpx
            references cablebrands,
    horizon_id            integer
        constraint fkaj49q6rig3mhhy4tgoa7ttqjp
            references horizons,
    incident_location_id  bigint
        constraint fkbgytsw2qdxoa5nkmd1hoo810l
            references locations,
    service_id            bigint
        constraint fksl4sm3dxnxwqecl8fj9uth7of
            references it_service_catalog,
    laying_method_id      bigint
        constraint fk4t6mofvoyyrwpb2u0ywxla9k1
            references layingmethods,
    fiber_name_id         bigint
        constraint fkho2gnurejoyx9anqxhlt7qmw9
            references optical_fiber_lines,
    line_type_id          bigint
        constraint fk9aptltenqqbfm5et4ar9jlxv1
            references optical_fiber_line_types,
    production_object_id  integer
        constraint fkmis3n0xsqa67uamuktw116s0x
            references productionobjects,
    request_type_id       bigint
        constraint fkgp2p7wg903f4lk8v2r89xngel
            references request_types,
    support_group_id      bigint
        constraint fkj08w858xwefo3id18yr06nhs7
            references supportgroup
);

alter table incidentrequests
    owner to postgres;

create table incident_request_causes
(
    request_id bigint not null
        constraint fk5wc02n8lulquuekay1bw7jsvv
            references incidentrequests,
    cause_id   bigint not null
        constraint fk2et18i4ejw5ija158ivkrvco8
            references incident_causes,
    primary key (request_id, cause_id)
);

alter table incident_request_causes
    owner to postgres;

create table requestprocessing
(
    request_id          integer generated by default as identity
        primary key,
    closing_datetime    timestamp,
    comment             varchar(255),
    material_costs      double precision,
    solution            varchar(255),
    incident_request_id bigint not null
        constraint fksbirggcjvwuhd63xp7napt1bq
            references incidentrequests,
    incident_status_id  bigint
        constraint fksvrntqdci3hqxe0p87eo8ld9t
            references incidentstatus,
    request_status_id   bigint
        constraint fksyo9fyqialx3q7hmpw2x4egst
            references requeststatus
);

alter table requestprocessing
    owner to postgres;

create table request_accepted_measures
(
    request_id integer not null
        constraint fk53e4nos08fbmvvwkmc40s2xcw
            references requestprocessing,
    measure_id bigint  not null
        constraint fkpqpy8n9yslin3uxa81gf7y93c
            references acceptedmeasures
);

alter table request_accepted_measures
    owner to postgres;

create table request_executors
(
    request_id  integer not null
        constraint fkjrj7lvorkr0167bf9ik45mi2m
            references requestprocessing,
    employee_id integer not null
        constraint fkpnb6epjusi8i4tiynbigj7sxc
            references employees
);

alter table request_executors
    owner to postgres;

create table request_extension_causes_junction
(
    request_id integer not null
        constraint fkkixsln8rna2e3b1us1qh8arrb
            references requestprocessing,
    cause_id   bigint  not null
        constraint fkcejvpi3ndcrrrcxmilctys16j
            references requestextensioncauses
);

alter table request_extension_causes_junction
    owner to postgres;

create table supportgroup_employee
(
    support_group_id bigint  not null
        constraint fktps99aj99etgu54swqgrq0vm4
            references supportgroup,
    employee_id      integer not null
        constraint fk2rx7qsce0vvr4g52ryn7sgvtb
            references employees,
    primary key (support_group_id, employee_id)
);

alter table supportgroup_employee
    owner to postgres;

create table users
(
    user_id     bigint generated by default as identity
        primary key,
    email       varchar(255) not null
        constraint uk_6dotkott2kjsp8vw4d0m25fb7
            unique,
    password    varchar(255) not null,
    role        varchar(255) not null,
    username    varchar(255) not null
        constraint uk_r43af9ap4edm43mmtq01oddj6
            unique,
    employee_id integer
        constraint fk6p2ib82uai0pj9yk1iassppgq
            references employees
);

alter table users
    owner to postgres;

create table token
(
    tokenid   bigint generated by default as identity
        primary key,
    expired   boolean      not null,
    revoked   boolean      not null,
    token     varchar(255),
    tokentype varchar(255) not null,
    userid    bigint
        constraint fkt38b0ovh80bxfch0tigpeki39
            references users
);

alter table token
    owner to postgres;

