spring:
  application:
    name: SapBackend
  datasource:
    url: jdbc:sap://7b84a113-20f9-49dc-b688-fbdd7ca88294.hna2.prod-eu10.hanacloud.ondemand.com:443
    username: DBADMIN
    password: Admin123!
    driver-class-name: com.sap.db.jdbc.Driver
#    username: 'postgres'
#    url: jdbc:postgresql://localhost:5432/sap
#    password: '0000'
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.HANAColumnStoreDialect
    hibernate:
      ddl-auto: update
    show-sql: true
#    show-sql: true
#    hibernate:
#      ddl-auto: update
server:
  port: 8090





application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#      expiration: 86400000
      expiration: 18748800000
      refresh-token:
        expiration: 604800000
